---
title: "Citibike"
author: "Tarun Bhadri, Ben Boeke, Taeyoung Justin Yun, Victor Manuel Jauregui-Tapia, Vincent Qu Dee"
date: "11/30/2021"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
```
```{r}
library(tidyverse)
library(gganimate)
library(geosphere)
library(lubridate)
library(ggplot2)
library(dplyr)
library(knitr)
library(leaflet)
```


## Data frame setup 
### Data Cleaning 
```{r}
#Start New RMD File for Analysis
#Reading the new csv file 
citisample <- read.csv("citibike.csv")
citisample$X <- NULL
citisample$start.station.id <- as.factor(citisample$start.station.id)
citisample$end.station.id <- as.factor(citisample$end.station.id)
citisample$bikeid <- as.factor(citisample$bikeid)
citisample$usertype <- as.factor(citisample$usertype)
citisample$gender <- as.factor(citisample$gender)
# Fix gender
citisample$gender <- ifelse(citisample$gender == 1, "male", ifelse(citisample$gender == 2, "female", "unknown"))
citisample$gender <- as.factor(citisample$gender)
# Create a column for approximate age
citisample$age <- 2021 - citisample$birth.year
```

### Data Cleaning Continued
```{r}
citisample$starttime <- as.POSIXct(strptime(citisample$starttime, "%Y-%m-%d %H:%M:%S"))
citisample$stoptime <- as.POSIXct(strptime(citisample$stoptime, "%Y-%m-%d %H:%M:%S"))

citisample$starthour <- hour(citisample$starttime)
citisample$day <- date(citisample$starttime)

citisample$month <- as.factor(month(citisample$day))

citisample$numWeekday <- wday(citisample$starttime)
citisample$dayid <- as.factor(ifelse(citisample$numWeekday < 6, "Weekday", "Weekend"))
citisample$weekNum <- week(citisample$starttime)
citisample$distmeters <- distHaversine(cbind(citisample$start.station.latitude, citisample$start.station.longitude), cbind(citisample$end.station.latitude, citisample$end.station.longitude))

citisample$speed <- citisample$distmeters / citisample$tripduration
str(citisample)
```
### Merging NYC Weather Data
```{r}
#Merging Datasets
weather <- read.csv("NYCWeather2019.csv")
weather$STATION <- NULL
weather$NAME <- NULL
weather$DATE <- as.Date(weather$DATE, format= "%m/%d/%Y")
weather$TAVG <- (weather$TMAX + weather$TMIN)/2

citiday <- citisample %>%
  group_by(day, gender, dayid) %>%
  summarize(count = n(),
            dist = mean(distmeters, na.rm = TRUE),
            dur = mean(tripduration, na.rm = TRUE),
            speed = dist/dur)

combined_gender <- merge(citiday, weather, by.x = "day", by.y = "DATE")
```
## Citi Bike Data Context 
```{r}
ggplot(citisample, aes(x=month)) + geom_bar() +labs( title = "Amount of Rides in 2019 per month")
```

```{r}
ggplot(citisample, aes(x=month, fill = gender)) + geom_bar(position=position_dodge()) +labs( title = "Amount of Rides in 2019 by gender")
```

```{r}
ggplot(citisample, aes(x=usertype)) + geom_bar(position=position_dodge()) +labs( title = "Subscriber v. Customer amount of rides in 2019")
```



## Assymetric Traffic 
```{r}
citisample$route <- paste(citisample$start.station.name,citisample$end.station.name,sep=" -> ")

citisample %>% 
  group_by(route) %>% 
  summarize(count=n()) %>% 
  arrange(desc(count)) %>% 
  top_n(n=10) %>% kable(format="markdown")
```


```{r}
bike_departures <- group_by(citisample, station = `start.station.name`, latitude = `start.station.latitude`, longitude = `start.station.longitude`)

departure <- summarise(bike_departures, departure_count = n())


bike_arrivals <- group_by(citisample, station = `end.station.name`, latitude = `end.station.latitude`, longitude = `end.station.longitude`)
arrival <- summarise(bike_arrivals, arrival_count = n())

#merge departure and arrival data into one df
bike_deficit <- merge(departure, arrival, all = TRUE)
# make NA's = 0
bike_deficit[is.na(bike_deficit)] <- 0

#make deficit variable: == arrivals - departures
bike_deficit$deficit <- bike_deficit$departure_count - bike_deficit$arrival_count
```

```{r}
#Now we are just going to show the 10% of most problematic stations. That means that we are only going to show the 10% of stations where the difference between arrivals and departures is higher
bike_deficit10percent<-sort(abs(bike_deficit$deficit),decreasing = TRUE)
minimum<-bike_deficit10percent[length(bike_deficit10percent)%/%10]

bike_deficit_worststations<-bike_deficit[abs(bike_deficit$deficit)>=minimum,]



# circle size representative of the magnitude of the deficit or surplus the station has (absolute val of how many more departures it has than arrivals)
# Red circles have a net deficit, blue circles have a net surplus
# click on station to see station name and net deficit or surplus
leaflet(bike_deficit_worststations) %>% 
  addTiles() %>%
  addCircleMarkers(lng = bike_deficit_worststations$longitude, lat = bike_deficit_worststations$latitude, 
                   popup = paste(bike_deficit_worststations$station, "<br>", ifelse(bike_deficit_worststations$deficit>=0, "Bike deficit = ", "Bike surplus = "), 
                                abs(bike_deficit_worststations$deficit)), 
                   radius = abs(bike_deficit_worststations$deficit)/5, color = ifelse(bike_deficit_worststations$deficit>0, "red", "green"))
```


```{r}
bike_deficit_10<-arrange(bike_deficit, (deficit))[1:10,]

str(bike_deficit_10)

leaflet(bike_deficit_10) %>% 
  addTiles() %>%
  addMarkers(lng = ~longitude, lat = ~latitude, label=paste(bike_deficit_10$station,bike_deficit_10$deficit))


bike_surplus_10<-arrange(bike_deficit, -deficit)[1:10,]

str(bike_surplus_10)

leaflet(bike_surplus_10) %>% 
  addTiles() %>%
  addMarkers(lng = ~longitude, lat = ~latitude, label=paste(bike_surplus_10$station,bike_surplus_10$deficit))

```




## Bike Usage 
### BikeID
```{r}
topbikes <- citisample %>%
  group_by(bikeid) %>%
  summarize(count=n()) %>%
  arrange(desc(count)) %>%
  top_n(n=10) %>% kable(format="markdown")
```


## Weather 

```{r}
ggplot(combined_gender, aes(x = TAVG, y = dist)) + geom_point(size = 2, alpha = 0.5, color = "yellowgreen") + geom_smooth(color = "darkgreen") + ylim(0,3000) 
```

```{r}
str(combined_gender)
combined_gender %>%
  group_by(PRCP) %>%
  summarize(count = n(),
            dist = mean(dist, na.rm = TRUE),
            avgprcp = mean(PRCP, na.rm = TRUE),
            speed = dist/dur) %>%
  ggplot(aes(x = PRCP,y = dist)) + geom_point() + geom_smooth()

```


### Does the ridership speed differ between months? 
```{r}
citisample %>%
  group_by(month) %>%
  summarize(count = n(),
            dist = mean(distmeters, na.rm = TRUE),
            dur = mean(tripduration, na.rm = TRUE),
            speed = dist/dur) %>%
  ggplot(aes(x=month, y = dist, fill = count)) + geom_col() +labs(y="Distance", title = "Avg Distance each Month" )
```
